import Head from 'next/head'
import Sidebar from '../components/Sidebar'
import Timeline from '../components/Timeline'

export default function Home() {
  return (
    <>
      <Head>
        <title>Twitterクローン</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="app">
        {/* Sidebar */}
        <Sidebar />
        {/* Timeline */}
        <Timeline />
        {/* Widget */}
      </div>
    </>
  )
}
